package com.antbean.photo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAlbum<M extends BaseAlbum<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setCoverUri(java.lang.String coverUri) {
		set("cover_uri", coverUri);
	}

	public java.lang.String getCoverUri() {
		return get("cover_uri");
	}

	public void setDesc(java.lang.String desc) {
		set("desc", desc);
	}

	public java.lang.String getDesc() {
		return get("desc");
	}

	public void setSize(java.lang.Integer size) {
		set("size", size);
	}

	public java.lang.Integer getSize() {
		return get("size");
	}

	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}

	public java.lang.Integer getSort() {
		return get("sort");
	}

	public void setIsDeleted(java.lang.Boolean isDeleted) {
		set("is_deleted", isDeleted);
	}

	public java.lang.Boolean getIsDeleted() {
		return get("is_deleted");
	}

	public void setGmtCreated(java.util.Date gmtCreated) {
		set("gmt_created", gmtCreated);
	}

	public java.util.Date getGmtCreated() {
		return get("gmt_created");
	}

	public void setGmtUpdate(java.util.Date gmtUpdate) {
		set("gmt_update", gmtUpdate);
	}

	public java.util.Date getGmtUpdate() {
		return get("gmt_update");
	}

}
