package com.antbean.photo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePhoto<M extends BasePhoto<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setDesc(java.lang.String desc) {
		set("desc", desc);
	}

	public java.lang.String getDesc() {
		return get("desc");
	}

	public void setUri(java.lang.String uri) {
		set("uri", uri);
	}

	public java.lang.String getUri() {
		return get("uri");
	}

	public void setIsVideo(java.lang.Boolean isVideo) {
		set("is_video", isVideo);
	}

	public java.lang.Boolean getIsVideo() {
		return get("is_video");
	}

	public void setMd5(java.lang.String md5) {
		set("md5", md5);
	}

	public java.lang.String getMd5() {
		return get("md5");
	}

	public void setWidth(java.lang.Integer width) {
		set("width", width);
	}

	public java.lang.Integer getWidth() {
		return get("width");
	}

	public void setHeight(java.lang.Integer height) {
		set("height", height);
	}

	public java.lang.Integer getHeight() {
		return get("height");
	}

	public void setSize(java.lang.Integer size) {
		set("size", size);
	}

	public java.lang.Integer getSize() {
		return get("size");
	}

	public void setIsDeleted(java.lang.Boolean isDeleted) {
		set("is_deleted", isDeleted);
	}

	public java.lang.Boolean getIsDeleted() {
		return get("is_deleted");
	}

	public void setGmtCreated(java.util.Date gmtCreated) {
		set("gmt_created", gmtCreated);
	}

	public java.util.Date getGmtCreated() {
		return get("gmt_created");
	}

	public void setGmtUpdate(java.util.Date gmtUpdate) {
		set("gmt_update", gmtUpdate);
	}

	public java.util.Date getGmtUpdate() {
		return get("gmt_update");
	}

}
