package com.antbean.photo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLink<M extends BaseLink<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setCoverUri(java.lang.String coverUri) {
		set("cover_uri", coverUri);
	}

	public java.lang.String getCoverUri() {
		return get("cover_uri");
	}

	public void setShortDesc(java.lang.String shortDesc) {
		set("short_desc", shortDesc);
	}

	public java.lang.String getShortDesc() {
		return get("short_desc");
	}

	public void setDesc(java.lang.String desc) {
		set("desc", desc);
	}

	public java.lang.String getDesc() {
		return get("desc");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setAlbumId(java.lang.Integer albumId) {
		set("album_id", albumId);
	}

	public java.lang.Integer getAlbumId() {
		return get("album_id");
	}

	public void setTags(java.lang.String tags) {
		set("tags", tags);
	}

	public java.lang.String getTags() {
		return get("tags");
	}

	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}

	public java.lang.Integer getSort() {
		return get("sort");
	}

	public void setIsDeleted(java.lang.Boolean isDeleted) {
		set("is_deleted", isDeleted);
	}

	public java.lang.Boolean getIsDeleted() {
		return get("is_deleted");
	}

	public void setGmtCreated(java.util.Date gmtCreated) {
		set("gmt_created", gmtCreated);
	}

	public java.util.Date getGmtCreated() {
		return get("gmt_created");
	}

	public void setGmtUpdate(java.util.Date gmtUpdate) {
		set("gmt_update", gmtUpdate);
	}

	public java.util.Date getGmtUpdate() {
		return get("gmt_update");
	}

}
