package com.antbean.photo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRAlbumPhoto<M extends BaseRAlbumPhoto<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setAlbumId(java.lang.Integer albumId) {
		set("album_id", albumId);
	}

	public java.lang.Integer getAlbumId() {
		return get("album_id");
	}

	public void setPhotoId(java.lang.Integer photoId) {
		set("photo_id", photoId);
	}

	public java.lang.Integer getPhotoId() {
		return get("photo_id");
	}

	public void setIsDeleted(java.lang.Boolean isDeleted) {
		set("is_deleted", isDeleted);
	}

	public java.lang.Boolean getIsDeleted() {
		return get("is_deleted");
	}

	public void setGmtCreated(java.util.Date gmtCreated) {
		set("gmt_created", gmtCreated);
	}

	public java.util.Date getGmtCreated() {
		return get("gmt_created");
	}

	public void setGmtUpdate(java.util.Date gmtUpdate) {
		set("gmt_update", gmtUpdate);
	}

	public java.util.Date getGmtUpdate() {
		return get("gmt_update");
	}

}
