package com.antbean.photo.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("r_album_photo", "id", AlbumPhoto.class);
		arp.addMapping("t_album", "id", Album.class);
		arp.addMapping("t_link", "id", Link.class);
		arp.addMapping("t_photo", "id", Photo.class);
	}
}

