package com.antbean.photo.model;

import com.antbean.photo.model.base.BaseAlbumPhoto;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AlbumPhoto extends BaseAlbumPhoto<AlbumPhoto> {
	public static final AlbumPhoto dao = new AlbumPhoto();
}
