package com.antbean.photo.model;

import com.antbean.photo.model.base.BaseAlbum;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Album extends BaseAlbum<Album> {
	public static final Album dao = new Album();
}
