package com.antbean.photo.model;

import com.antbean.photo.model.base.BaseLink;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Link extends BaseLink<Link> {
	public static final Link dao = new Link();
}
