package com.antbean.photo.model;

import com.antbean.photo.model.base.BasePhoto;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Photo extends BasePhoto<Photo> {
	public static final Photo dao = new Photo();
}
