package com.antbean.photo.model;

import com.antbean.photo.model.base.BaseRAlbumPhoto;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RAlbumPhoto extends BaseRAlbumPhoto<RAlbumPhoto> {
	public static final RAlbumPhoto dao = new RAlbumPhoto();
}
